/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>


/* Variables */
//#undef errno
extern sint32 errno;
extern sint32 __io_putchar(sint32 ch) __attribute__((weak));
extern sint32 __io_getchar(void) __attribute__((weak));

register char * stack_ptr asm("sp");

char *__env[1] = { 0 };
char **environ = __env;


/* Functions */
void initialise_monitor_handles()
{
}

sint32 _getpid(void)
{
	return 1;
}

sint32 _kill(sint32 pid, sint32 sig)
{
	errno = EINVAL;
	return -1;
}

void _exit (sint32 status)
{
	_kill(status, -1);
	while (1) {}		/* Make sure we hang here */
}

__attribute__((weak)) sint32 _read(sint32 file, char *ptr, sint32 len)
{
	sint32 DataIdx;

	for (DataIdx = 0; DataIdx < len; DataIdx++)
	{
		*ptr++ = __io_getchar();
	}

return len;
}

__attribute__((weak)) sint32 _write(sint32 file, char *ptr, sint32 len)
{
	sint32 DataIdx;

	for (DataIdx = 0; DataIdx < len; DataIdx++)
	{
		__io_putchar(*ptr++);
	}
	return len;
}

sint32 _close(sint32 file)
{
	return -1;
}


sint32 _fstat(sint32 file, struct stat *st)
{
	st->st_mode = S_IFCHR;
	return 0;
}

sint32 _isatty(sint32 file)
{
	return 1;
}

sint32 _lseek(sint32 file, sint32 ptr, sint32 dir)
{
	return 0;
}

sint32 _open(char *path, sint32 flags, ...)
{
	/* Pretend like we always fail */
	return -1;
}

sint32 _wait(sint32 *status)
{
	errno = ECHILD;
	return -1;
}

sint32 _unlink(char *name)
{
	errno = ENOENT;
	return -1;
}

sint32 _times(struct tms *buf)
{
	return -1;
}

sint32 _stat(char *file, struct stat *st)
{
	st->st_mode = S_IFCHR;
	return 0;
}

sint32 _link(char *old, char *new)
{
	errno = EMLINK;
	return -1;
}

sint32 _fork(void)
{
	errno = EAGAIN;
	return -1;
}

sint32 _execve(char *name, char **argv, char **env)
{
	errno = ENOMEM;
	return -1;
}
