#include "P_BattStatusFlag_Tx_To_SWC_BMS_Status.h"

void P_BattStatusFlag_Tx_To_SWC_BMS_Status_Write(f_Voltage voltageFaultFlags, f_Temp tempFaultFlags,f_Current currentFaultFlags, f_Ibp ibpFaultFlags, f_IsolResist packIsolationFaultFlag, boolean cellBalancingFlag)
{
    Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlag_Tx_voltageFaultFlags(voltageFaultFlags);
    Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlag_Tx_tempFaultFlags(tempFaultFlags);
    Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlag_Tx_currentFaultFlags(currentFaultFlags);
    Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlag_Tx_ibpFaultFlags(ibpFaultFlags);
    Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlag_Tx_packIsolationFaultFlag(packIsolationFaultFlag);
    Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlag_Tx_cellBalancingFlag(cellBalancingFlag);
}   