#ifndef RTE_SWC_BMS_MAINCNTRL_H
#define RTE_SWC_BMS_MAINCNTRL_H

#include "Rte_SWC_BMS_MainCntrl_Type.h"

#define Rte_Call_R_CellBalanceReq_cellBalanceDisable Rte_Call_SWC_BMS_MainCntrl_R_CellBalanceReq_cellBalanceDisable
#define Rte_Call_R_CellBalanceReq_cellBalanceEnable Rte_Call_SWC_BMS_MainCntrl_R_CellBalanceReq_cellBalanceEnable
#define Rte_Call_R_ChgData_chargeSequenceCtrl Rte_Call_SWC_BMS_MainCntrl_R_ChgData_chargeSequenceCtrl
#define Rte_Call_R_RelayControlReq_relayDisableReq Rte_Call_SWC_BMS_MainCntrl_R_RelayControlReq_relayDisableReq
#define Rte_Call_R_RelayControlReq_relayEnableReq Rte_Call_SWC_BMS_MainCntrl_R_RelayControlReq_relayEnableReq
#define Rte_Call_R_SocCalc_calculateCapacity Rte_Call_SWC_BMS_MainCntrl_R_SocCalc_calculateCapacity
#define Rte_Call_R_SocCalc_calculateSoc Rte_Call_SWC_BMS_MainCntrl_R_SocCalc_calculateSoc
#define Rte_Call_R_SocCalc_calculateSoh Rte_Call_SWC_BMS_MainCntrl_R_SocCalc_calculateSoh
#define Rte_Read_R_CellMeasData_cellSerialNum Rte_Read_SWC_BMS_MainCntrl_R_CellMeasData_cellSerialNum
#define Rte_Read_R_CellMeasData_cellVoltageAverage Rte_Read_SWC_BMS_MainCntrl_R_CellMeasData_cellVoltageAverage
#define Rte_Read_R_CellMeasData_cellVoltageIndividual Rte_Read_SWC_BMS_MainCntrl_R_CellMeasData_cellVoltageIndividual
#define Rte_Read_R_CellMeasData_cellVoltageMax Rte_Read_SWC_BMS_MainCntrl_R_CellMeasData_cellVoltageMax
#define Rte_Read_R_CellMeasData_cellVoltageMin Rte_Read_SWC_BMS_MainCntrl_R_CellMeasData_cellVoltageMin
#define Rte_Read_R_CellMeasData_ibpLevel Rte_Read_SWC_BMS_MainCntrl_R_CellMeasData_ibpLevel
#define Rte_Read_R_CellMeasData_packVoltageSum Rte_Read_SWC_BMS_MainCntrl_R_CellMeasData_packVoltageSum
#define Rte_Read_R_CurrMeasData_packCurrent Rte_Read_SWC_BMS_MainCntrl_R_CurrMeasData_packCurrent
#define Rte_Read_R_FaultFlag_errChargeOverTemp Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errChargeOverTemp
#define Rte_Read_R_FaultFlag_errChargeUnderTemp Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errChargeUnderTemp
#define Rte_Read_R_FaultFlag_errDischargeOverTemp Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errDischargeOverTemp
#define Rte_Read_R_FaultFlag_errDischargeUnderTemp Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errDischargeUnderTemp
#define Rte_Read_R_FaultFlag_errIsolation Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errIsolation
#define Rte_Read_R_FaultFlag_errOverCellVmax Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errOverCellVmax
#define Rte_Read_R_FaultFlag_errOverCharge Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errOverCharge
#define Rte_Read_R_FaultFlag_errOverChargeCurrent Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errOverChargeCurrent
#define Rte_Read_R_FaultFlag_errOverDischarge Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errOverDischarge
#define Rte_Read_R_FaultFlag_errOverDischargeCurrent Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errOverDischargeCurrent
#define Rte_Read_R_FaultFlag_errOverIbp Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errOverIbp
#define Rte_Read_R_FaultFlag_errUnderCellVmin Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errUnderCellVmin
#define Rte_Read_R_FaultFlag_warnChargeOverTemp Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnChargeOverTemp
#define Rte_Read_R_FaultFlag_warnChargeUnderTemp Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnChargeUnderTemp
#define Rte_Read_R_FaultFlag_warnDischargeOverTemp Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnDischargeOverTemp
#define Rte_Read_R_FaultFlag_warnDischargeUnderTemp Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnDischargeUnderTemp
#define Rte_Read_R_FaultFlag_warnOverCellVmax Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnOverCellVmax
#define Rte_Read_R_FaultFlag_warnOverCharge Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnOverCharge
#define Rte_Read_R_FaultFlag_warnOverChargeCurrent Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnOverChargeCurrent
#define Rte_Read_R_FaultFlag_warnOverDisCharge Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnOverDisCharge
#define Rte_Read_R_FaultFlag_warnOverDischargeCurrent Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnOverDischargeCurrent
#define Rte_Read_R_FaultFlag_warnOverIbp Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnOverIbp
#define Rte_Read_R_FaultFlag_warnUnderCellVmin Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnUnderCellVmin
#define Rte_Read_R_SignalInput_chargeConnectedFlag Rte_Read_SWC_BMS_MainCntrl_R_SignalInput_chargeConnectedFlag
#define Rte_Read_R_SignalInput_ignSignal Rte_Read_SWC_BMS_MainCntrl_R_SignalInput_ignSignal
#define Rte_Read_R_TempMeasData_cellTempAverage Rte_Read_SWC_BMS_MainCntrl_R_TempMeasData_cellTempAverage
#define Rte_Read_R_TempMeasData_cellTempMax Rte_Read_SWC_BMS_MainCntrl_R_TempMeasData_cellTempMax
#define Rte_Read_R_TempMeasData_cellTempMin Rte_Read_SWC_BMS_MainCntrl_R_TempMeasData_cellTempMin
#define Rte_Read_R_VcuCanCmd_bmsActionCmd Rte_Read_SWC_BMS_MainCntrl_R_VcuCanCmd_bmsActionCmd
#define Rte_Write_P_BattStatusFlags_Tx_cellBalancingFlag Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlags_Tx_cellBalancingFlag
#define Rte_Write_P_BattStatusFlags_Tx_currentFaultFlags Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlags_Tx_currentFaultFlags
#define Rte_Write_P_BattStatusFlags_Tx_ibpFaultFlags Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlags_Tx_ibpFaultFlags
#define Rte_Write_P_BattStatusFlags_Tx_packIsolationFaultFlag Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlags_Tx_packIsolationFaultFlag
#define Rte_Write_P_BattStatusFlags_Tx_tempFaultFlags Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlags_Tx_tempFaultFlags
#define Rte_Write_P_BattStatusFlags_Tx_voltageFaultFlags Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlags_Tx_voltageFaultFlags
#define Rte_Write_P_ChgData_Tx_chargingStatus Rte_Write_SWC_BMS_MainCntrl_P_ChgData_Tx_chargingStatus
#define Rte_Write_P_ChgData_Tx_chgTargetCurrent Rte_Write_SWC_BMS_MainCntrl_P_ChgData_Tx_chgTargetCurrent
#define Rte_Write_P_ChgData_Tx_chgTargetVoltage Rte_Write_SWC_BMS_MainCntrl_P_ChgData_Tx_chgTargetVoltage
#define Rte_Write_P_HMI_SigOutput_battRalayEnableStatus Rte_Write_SWC_BMS_MainCntrl_P_HMI_SigOutput_battRalayEnableStatus
#define Rte_Write_P_HMI_SigOutput_bmsFaultLevel Rte_Write_SWC_BMS_MainCntrl_P_HMI_SigOutput_bmsFaultLevel
#define Rte_Write_P_HMI_SigOutput_buzzerOutputFlag Rte_Write_SWC_BMS_MainCntrl_P_HMI_SigOutput_buzzerOutputFlag
#define Rte_Write_P_HMI_SigOutput_chargingStatus Rte_Write_SWC_BMS_MainCntrl_P_HMI_SigOutput_chargingStatus
#define Rte_Write_P_HMI_SigOutput_socGauge Rte_Write_SWC_BMS_MainCntrl_P_HMI_SigOutput_socGauge
#define Rte_Write_P_PackCalculatedData_Tx_capacityLevel Rte_Write_SWC_BMS_MainCntrl_P_PackCalculatedData_Tx_capacityLevel
#define Rte_Write_P_PackCalculatedData_Tx_ibpLevel Rte_Write_SWC_BMS_MainCntrl_P_PackCalculatedData_Tx_ibpLevel
#define Rte_Write_P_PackCalculatedData_Tx_socLevel Rte_Write_SWC_BMS_MainCntrl_P_PackCalculatedData_Tx_socLevel
#define Rte_Write_P_PackCalculatedData_Tx_sohLevel Rte_Write_SWC_BMS_MainCntrl_P_PackCalculatedData_Tx_sohLevel
#define Rte_Write_P_PackMeasData_Tx_bmsModeInfo Rte_Write_SWC_BMS_MainCntrl_P_PackMeasData_Tx_bmsModeInfo
#define Rte_Write_P_PackMeasData_Tx_cellTempAverage Rte_Write_SWC_BMS_MainCntrl_P_PackMeasData_Tx_cellTempAverage
#define Rte_Write_P_PackMeasData_Tx_packCurrent Rte_Write_SWC_BMS_MainCntrl_P_PackMeasData_Tx_packCurrent
#define Rte_Write_P_PackMeasData_Tx_packVoltageSum Rte_Write_SWC_BMS_MainCntrl_P_PackMeasData_Tx_packVoltageSum

extern CONSTP2CONST(Rte_CDS_SWC_BMS_MainCntrl, RTE_CONST, RTE_CONST) Rte_Inst_SWC_BMS_MainCntrl;

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_BMS_MainCntrl_R_CellBalanceReq_cellBalanceDisable();
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_BMS_MainCntrl_R_CellBalanceReq_cellBalanceEnable(P2CONST(uint16, AUTOMATIC, RTE_APPL_CONST) cellVoltageIndividual, VAR(uint16, AUTOMATIC) targetIbpLevel);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_BMS_MainCntrl_R_ChgData_chargeSequenceCtrl(P2VAR(uint32, AUTOMATIC, RTE_APPL_DATA) chgTargetVoltage, P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) chgTargetCurrent, P2VAR(e_ChgInfo, AUTOMATIC, RTE_APPL_DATA) chargingStatus);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_BMS_MainCntrl_R_RelayControlReq_relayDisableReq();
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_BMS_MainCntrl_R_RelayControlReq_relayEnableReq(VAR(e_relayEnableSpeed, AUTOMATIC) speed);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_BMS_MainCntrl_R_SocCalc_calculateCapacity(P2VAR(uint32, AUTOMATIC, RTE_APPL_DATA) calculatedCapacity);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_BMS_MainCntrl_R_SocCalc_calculateSoc(P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) calculatedSocValue);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_SWC_BMS_MainCntrl_R_SocCalc_calculateSoh(P2VAR(uint32, AUTOMATIC, RTE_APPL_DATA) calculateSohValue);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_CellMeasData_cellSerialNum(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) cellSerialNum);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_CellMeasData_cellVoltageAverage(P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) cellVoltageAverage);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_CellMeasData_cellVoltageIndividual(P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) cellVoltageIndividual);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_CellMeasData_cellVoltageMax(P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) cellVoltageMax);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_CellMeasData_cellVoltageMin(P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) cellVoltageMin);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_CellMeasData_ibpLevel(P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) ibpLevel);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_CellMeasData_packVoltageSum(P2VAR(uint32, AUTOMATIC, RTE_APPL_DATA) packVoltageSum);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_CurrMeasData_packCurrent(P2VAR(sint32, AUTOMATIC, RTE_APPL_DATA) packCurrent);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errChargeOverTemp(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) errChargeOverTemp);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errChargeUnderTemp(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) errChargeUnderTemp);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errDischargeOverTemp(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) errDischargeOverTemp);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errDischargeUnderTemp(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) errDischargeUnderTemp);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errIsolation(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) errIsolation);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errOverCellVmax(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) errOverCellVmax);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errOverCharge(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) errOverCharge);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errOverChargeCurrent(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) errOverChargeCurrent);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errOverDischarge(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) errOverDischarge);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errOverDischargeCurrent(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) errOverDischargeCurrent);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errOverIbp(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) errOverIbp);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_errUnderCellVmin(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) errUnderCellVmin);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnChargeOverTemp(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) warnChargeOverTemp);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnChargeUnderTemp(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) warnChargeUnderTemp);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnDischargeOverTemp(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) warnDischargeOverTemp);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnDischargeUnderTemp(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) warnDischargeUnderTemp);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnOverCellVmax(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) warnOverCellVmax);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnOverCharge(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) warnOverCharge);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnOverChargeCurrent(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) warnOverChargeCurrent);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnOverDisCharge(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) warnOverDisCharge);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnOverDischargeCurrent(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) warnOverDischargeCurrent);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnOverIbp(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) warnOverIbp);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_FaultFlag_warnUnderCellVmin(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) warnUnderCellVmin);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_SignalInput_chargeConnectedFlag(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) chargeConnectedFlag);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_SignalInput_ignSignal(P2VAR(e_IgnStat, AUTOMATIC, RTE_APPL_DATA) ignSignal);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_TempMeasData_cellTempAverage(P2VAR(sint16, AUTOMATIC, RTE_APPL_DATA) cellTempAverage);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_TempMeasData_cellTempMax(P2VAR(sint16, AUTOMATIC, RTE_APPL_DATA) cellTempMax);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_TempMeasData_cellTempMin(P2VAR(sint16, AUTOMATIC, RTE_APPL_DATA) cellTempMin);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_MainCntrl_R_VcuCanCmd_bmsActionCmd(P2VAR(e_VcuCanCmd, AUTOMATIC, RTE_APPL_DATA) bmsActionCmd);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlags_Tx_cellBalancingFlag(VAR(boolean, AUTOMATIC) cellBalancingFlag);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlags_Tx_currentFaultFlags(P2CONST(f_Current, AUTOMATIC, RTE_APPL_CONST) currentFaultFlags);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlags_Tx_ibpFaultFlags(P2CONST(f_Ibp, AUTOMATIC, RTE_APPL_CONST) ibpFaultFlags);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlags_Tx_packIsolationFaultFlag(P2CONST(f_IsolResist, AUTOMATIC, RTE_APPL_CONST) packIsolationFaultFlag);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlags_Tx_tempFaultFlags(P2CONST(f_Temp, AUTOMATIC, RTE_APPL_CONST) tempFaultFlags);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_BattStatusFlags_Tx_voltageFaultFlags(P2CONST(f_Voltage, AUTOMATIC, RTE_APPL_CONST) voltageFaultFlags);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_ChgData_Tx_chargingStatus(VAR(e_ChgInfo, AUTOMATIC) chargingStatus);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_ChgData_Tx_chgTargetCurrent(VAR(uint16, AUTOMATIC) chgTargetCurrent);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_ChgData_Tx_chgTargetVoltage(VAR(uint32, AUTOMATIC) chgTargetVoltage);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_HMI_SigOutput_battRalayEnableStatus(VAR(boolean, AUTOMATIC) battRalayEnableStatus);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_HMI_SigOutput_bmsFaultLevel(VAR(e_FaultLevel, AUTOMATIC) bmsFaultLevel);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_HMI_SigOutput_buzzerOutputFlag(VAR(boolean, AUTOMATIC) buzzerOutputFlag);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_HMI_SigOutput_chargingStatus(VAR(e_ChgInfo, AUTOMATIC) chargingStatus);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_HMI_SigOutput_socGauge(VAR(uint8, AUTOMATIC) socGauge);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_PackCalculatedData_Tx_capacityLevel(VAR(uint16, AUTOMATIC) capacityLevel);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_PackCalculatedData_Tx_ibpLevel(VAR(uint16, AUTOMATIC) ibpLevel);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_PackCalculatedData_Tx_socLevel(VAR(uint16, AUTOMATIC) socLevel);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_PackCalculatedData_Tx_sohLevel(VAR(uint32, AUTOMATIC) sohLevel);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_PackMeasData_Tx_bmsModeInfo(VAR(e_VcuCanCmd, AUTOMATIC) bmsModeInfo);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_PackMeasData_Tx_cellTempAverage(VAR(sint16, AUTOMATIC) cellTempAverage);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_PackMeasData_Tx_packCurrent(VAR(sint32, AUTOMATIC) packCurrent);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_SWC_BMS_MainCntrl_P_PackMeasData_Tx_packVoltageSum(VAR(uint32, AUTOMATIC) packVoltageSum);
FUNC(void, SWC_BMS_MainCntrl_CODE) REtSWC_BMS_MainCntrl_BattStatusProcess_10ms();
FUNC(void, SWC_BMS_MainCntrl_CODE) REtSWC_BMS_MainCntrl_SoX_1000ms();
FUNC(void, SWC_BMS_MainCntrl_CODE) REtSWC_BMS_MainCntrl_PerfomCellBalancing_1000ms();
FUNC(void, SWC_BMS_MainCntrl_CODE) REtSWC_BMS_MainCntrl_ChargeSequence_100ms();
FUNC(void, SWC_BMS_MainCntrl_CODE) REtSWC_BMS_MainCntrl_HMI_Output_100ms();
FUNC(void, SWC_BMS_MainCntrl_CODE) REtSWC_BMS_MainCntrl_ReportBattInfoData_10ms();

#endif