#ifndef RTE_SWC_BMS_STATUS_TX_H
#define RTE_SWC_BMS_STATUS_TX_H

#include "Rte_SWC_BMS_Status_Tx_Type.h"

#define Rte_Read_R_BattStatusFlags_Tx_cellBalancingFlag Rte_Read_SWC_BMS_Status_Tx_R_BattStatusFlags_Tx_cellBalancingFlag
#define Rte_Read_R_BattStatusFlags_Tx_currentFaultFlags Rte_Read_SWC_BMS_Status_Tx_R_BattStatusFlags_Tx_currentFaultFlags
#define Rte_Read_R_BattStatusFlags_Tx_ibpFaultFlags Rte_Read_SWC_BMS_Status_Tx_R_BattStatusFlags_Tx_ibpFaultFlags
#define Rte_Read_R_BattStatusFlags_Tx_packIsolationFaultFlag Rte_Read_SWC_BMS_Status_Tx_R_BattStatusFlags_Tx_packIsolationFaultFlag
#define Rte_Read_R_BattStatusFlags_Tx_tempFaultFlags Rte_Read_SWC_BMS_Status_Tx_R_BattStatusFlags_Tx_tempFaultFlags
#define Rte_Read_R_BattStatusFlags_Tx_voltageFaultFlags Rte_Read_SWC_BMS_Status_Tx_R_BattStatusFlags_Tx_voltageFaultFlags
#define Rte_Read_R_ChgData_Tx_chargingStatus Rte_Read_SWC_BMS_Status_Tx_R_ChgData_Tx_chargingStatus
#define Rte_Read_R_ChgData_Tx_chgTargetCurrent Rte_Read_SWC_BMS_Status_Tx_R_ChgData_Tx_chgTargetCurrent
#define Rte_Read_R_ChgData_Tx_chgTargetVoltage Rte_Read_SWC_BMS_Status_Tx_R_ChgData_Tx_chgTargetVoltage
#define Rte_Read_R_PackCalculatedData_Tx_capacityLevel Rte_Read_SWC_BMS_Status_Tx_R_PackCalculatedData_Tx_capacityLevel
#define Rte_Read_R_PackCalculatedData_Tx_ibpLevel Rte_Read_SWC_BMS_Status_Tx_R_PackCalculatedData_Tx_ibpLevel
#define Rte_Read_R_PackCalculatedData_Tx_socLevel Rte_Read_SWC_BMS_Status_Tx_R_PackCalculatedData_Tx_socLevel
#define Rte_Read_R_PackCalculatedData_Tx_sohLevel Rte_Read_SWC_BMS_Status_Tx_R_PackCalculatedData_Tx_sohLevel
#define Rte_Read_R_PackMeasData_Tx_bmsModeInfo Rte_Read_SWC_BMS_Status_Tx_R_PackMeasData_Tx_bmsModeInfo
#define Rte_Read_R_PackMeasData_Tx_cellTempAverage Rte_Read_SWC_BMS_Status_Tx_R_PackMeasData_Tx_cellTempAverage
#define Rte_Read_R_PackMeasData_Tx_packCurrent Rte_Read_SWC_BMS_Status_Tx_R_PackMeasData_Tx_packCurrent
#define Rte_Read_R_PackMeasData_Tx_packVoltageSum Rte_Read_SWC_BMS_Status_Tx_R_PackMeasData_Tx_packVoltageSum

extern CONSTP2CONST(Rte_CDS_SWC_BMS_Status_Tx, RTE_CONST, RTE_CONST) Rte_Inst_SWC_BMS_Status_Tx;

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_BattStatusFlags_Tx_cellBalancingFlag(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) cellBalancingFlag);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_BattStatusFlags_Tx_currentFaultFlags(P2VAR(f_Current, AUTOMATIC, RTE_APPL_DATA) currentFaultFlags);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_BattStatusFlags_Tx_ibpFaultFlags(P2VAR(f_Ibp, AUTOMATIC, RTE_APPL_DATA) ibpFaultFlags);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_BattStatusFlags_Tx_packIsolationFaultFlag(P2VAR(f_IsolResist, AUTOMATIC, RTE_APPL_DATA) packIsolationFaultFlag);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_BattStatusFlags_Tx_tempFaultFlags(P2VAR(f_Temp, AUTOMATIC, RTE_APPL_DATA) tempFaultFlags);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_BattStatusFlags_Tx_voltageFaultFlags(P2VAR(f_Voltage, AUTOMATIC, RTE_APPL_DATA) voltageFaultFlags);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_ChgData_Tx_chargingStatus(P2VAR(e_ChgInfo, AUTOMATIC, RTE_APPL_DATA) chargingStatus);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_ChgData_Tx_chgTargetCurrent(P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) chgTargetCurrent);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_ChgData_Tx_chgTargetVoltage(P2VAR(uint32, AUTOMATIC, RTE_APPL_DATA) chgTargetVoltage);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_PackCalculatedData_Tx_capacityLevel(P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) capacityLevel);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_PackCalculatedData_Tx_ibpLevel(P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) ibpLevel);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_PackCalculatedData_Tx_socLevel(P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) socLevel);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_PackCalculatedData_Tx_sohLevel(P2VAR(uint32, AUTOMATIC, RTE_APPL_DATA) sohLevel);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_PackMeasData_Tx_bmsModeInfo(P2VAR(e_VcuCanCmd, AUTOMATIC, RTE_APPL_DATA) bmsModeInfo);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_PackMeasData_Tx_cellTempAverage(P2VAR(sint16, AUTOMATIC, RTE_APPL_DATA) cellTempAverage);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_PackMeasData_Tx_packCurrent(P2VAR(sint32, AUTOMATIC, RTE_APPL_DATA) packCurrent);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_SWC_BMS_Status_Tx_R_PackMeasData_Tx_packVoltageSum(P2VAR(uint32, AUTOMATIC, RTE_APPL_DATA) packVoltageSum);
FUNC(void, SWC_BMS_Status_Tx_CODE) REtSWC_BMS_Status_Tx_GetBatStFlg_20ms();
FUNC(void, SWC_BMS_Status_Tx_CODE) REtSWC_BMS_Status_Tx_GetPackCalData_50ms();
FUNC(void, SWC_BMS_Status_Tx_CODE) REtSWC_BMS_Status_Tx_GetData_10ms();

#endif